apiVersion: v1
kind: Service
metadata:
  name: rclipredis
spec:
  selector:
    app: rclipredis-app
  ports:
  - protocol: TCP
    port: 6379
    targetPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: rclipapi
spec:
  selector:
    app: rclipapi-app
  type: LoadBalancer
  ports:
  - port: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rclipredis-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rclipredis-app
  template:
    metadata:
      labels:
        app: rclipredis-app
    spec:
      containers:
      - name: redis
        image: redis:latest
        ports:
        - containerPort: 6379
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rclipapi-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rclipapi-app
  template:
    metadata:
      labels:
        app: rclipapi-app
    spec:
      containers:
      - name: api
        image: ${RCLIPAPI_IMAGE}
        ports:
        - containerPort: 80
        env:
        - name: REDIS_HOST
          value: "rclipredis"
        - name: REDIS_TTL
          value: "30"
