version: '3'
services:
  rclipredis:
    image: redis:latest
    container_name: rclipredis
    ports:
    - '6379:6379'
  rclipapi:
    image: ${ACR_REPO}/rclipapi:latest
    container_name: rclipapi
    build: api
    environment:
    - REDIS_HOST=rclipredis
    - REDIS_TTL=30
    ports:
    - '80:80'

