version: '3'
services:
  rclipredis:
    image: redis:latest
    container_name: rclipredis
  rclipapi:
    container_name: rclipapi
    build:
        context: .
        dockerfile: Dockerfile
    environment:
    - REDIS_HOST=rclipredis
    - REDIS_TTL=30
    - REDIS_TTL_FILE=600
    ports:
    - '80:80'
    volumes:
      - type: bind
        source: ./logs
        target: /logs
