version: '3'
services:
  rclipredis:
    image: redis:latest
    container_name: rclipredis
  rclipapi:
    image: ${RCLIPAPI_IMAGE}
    container_name: rclipapi
    build: .
    environment:
    - REDIS_HOST=rclipredis
    - REDIS_TTL=30
    ports:
    - '80:80'

