services:
  rclipredis:
    image: redis:latest
    container_name: rclipredis
    restart: always
  rclipapi:
    container_name: rclipapi
    restart: always
    build:
        context: .
        dockerfile: Dockerfile
        args:
          - PORT=${PORT}
    environment:
      - REDIS_HOST=rclipredis
      - REDIS_TTL=${REDIS_TTL:-30}
      - KEY_WIDTH=${KEY_WIDTH:-3}
      - PORT=${PORT:-80}
      - EXPOSED_PORT=${EXPOSED_PORT:-80}
    ports:
      - '${EXPOSED_PORT}:${PORT}'
    volumes:
      - type: bind
        source: ./logs
        target: /logs
